apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  annotations:
    manifestival: new
  generation: 6
  name: gitops
  namespace: kabanero
spec:
  inputs:
    params:
      - default: 'docker.io/node:12-stretch'
        name: js-image
        type: string
      - default: docker.io/csantanapr/helm-kubectl
        name: tools-image
        type: string
    resources:
      - name: source
        type: git
      - name: image
        type: image
  steps:
    - args:
        - '-c'
        - >
          set -e

          # echo "applicationImage: bbb" > randomtext.txt

          # clone repo
          git clone https://github.com/ibm-cloud-architecture/devops-demo-dev-env.git

          cd devops-demo-dev-env

          # update value for key applicationImage
          sed -i '/image:/c\        image: $(inputs.resources.image.url)' ./deployment.yaml


          # verify the value for key applicationImage got updated
          cat ./deployment.yaml | grep "image"

          # This email is not used and it not valid, you can ignore but git requires it
          git config --global user.email "user@example.com"
          git config --global user.name "user"

          echo $(inputs.resources.source.path)
          # push changes to git
          git add .
          git commit -m "Updated deployment.yaml"
          git push
      command:
        - /bin/bash
      image: $(inputs.params.js-image)
      name: clone-update-repo
      resources: {}
      workingDir: $(inputs.resources.source.path)
