apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gitops-pr
spec:
  inputs:
    params:
    - default: docker.io/node:12-stretch
      name: js-image
      type: string
    - default: docker.io/csantanapr/helm-kubectl
      name: tools-image
      type: string
    resources:
    - name: source
      type: git
    - name: image
      type: image
  steps:
  - args:
    - -c
    - |
      set -e

      echo "Cloning the gitops repository"

      GIT_USER_ACCOUNT=hollisc
      GITHUB_API_TOKEN=360c8389f9b1f18db845f5d750de33c46a3f2a4e

      # clone repo
      git init
      git clone https://${GIT_USER_ACCOUNT}:${GITHUB_API_TOKEN}@github.com/ibm-cloud-architecture/devops-demo-qa-env.git
      cd devops-demo-qa-env
      git checkout -b ci-pipeline

      # update value for key applicationImage
      #sed -i "/applicationImage: /c\applicationImage: $(inputs.resources.image.url)" ./app-deploy.yaml
      sed -i "/image: /c\        image: $(inputs.resources.image.url)" deployment.yaml

      # verify the value for key applicationImage got updated
      #cat ./app-deploy.yaml | grep "applicationImage"
      cat deployment.yaml | grep "image"

      # push changes to git
      # This email is not used and it not valid, you can ignore but git requires it
      git config --global user.email "user@example.com"
      git config --global user.name "user"

      echo $(inputs.resources.source.path)
      git add .
      git commit -m "Tekton CI commit"
      git remote rm origin
      git remote add origin https://${GIT_USER_ACCOUNT}:360c8389f9b1f18db845f5d750de33c46a3f2a4e@github.com/ibm-cloud-architecture/devops-demo-qa-env.git > /dev/null 2>&1
      git push origin ci-pipeline

      curl -u hollisc:${GITHUB_API_TOKEN} -d '{"title":"PR to promote $(inputs.resources.image.url) to QA","base":"master", "head":"ibm-cloud-architecture:ci-pipeline"}' https://api.github.com/repos/ibm-cloud-architecture/devops-demo-qa-env/pulls
    command:
    - /bin/bash
    image: $(inputs.params.js-image)
    name: clone-update-repo
    resources: {}
    workingDir: $(inputs.resources.source.path)
