apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: send-to-webhook-slack
spec:
  inputs:
    params:
    - description: seret name of the slcak app webhook URL (key is url)
      name: webhook-secret
      type: string
    - description: plain text message
      name: message
      type: string
    resources:
    - name: image
      type: image
  steps:
  - env:
    - name: URL
      valueFrom:
        secretKeyRef:
          key: url
          name: $(inputs.params.webhook-secret)
    image: curlimages/curl:7.68.0
    name: post
    resources: {}
    script: |
      #!/bin/sh
      /usr/bin/curl -X POST -H 'Content-type: application/json' --data '{"text":"$(inputs.params.message)"}' $URL
