apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: package-pipelines-task
  namespace: kabanero
  author: Oscar I. Ricaud
  date: 04/21/20
spec:
  inputs:
    params:
      - default: googlefu/apic_compiler:v3-amd64
        name: asuh-image
        type: string
    resources:
      - name: source
        type: git
      - name: image
        type: image
  steps:
    - args:
        - -c
        - |
          set -e
          git clone https://github.com/oiricaud/pipelines temp
          cd temp/ci/
          # ./env.sh
          ./package.sh
          # ./release.sh
      command:
        - /bin/bash
      resources: {}
      name: package-pipelines-task
      image: $(inputs.params.asuh-image)
      workingDir: $(inputs.resources.source.path)

